Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App
      CodeUri: D:\GitHub\duongkha.github.io\WAA\FirstAWSServerlessApp\HelloWorldFunction
      Runtime: java8.al2